### Get Request
GET http://localhost:8080/api/runs
Accept: application/json

### Post Request
POST http://localhost:8080/api/runs/create
Content-Type: application/json

{
    "id": 11,
    "title": "Marathon Run",
    "startedOn": "2024-10-05T20:58:58",
    "completedOn": "2024-10-05T21:58:58",
    "miles": 15,
    "location": "OUTDOOR"
}

### Get Request
GET http://localhost:8080/api/runs/1
Content-Type: application/json

### Get Request Find Id that does not exist
GET http://localhost:8080/api/runs/99
Content-Type: application/json
























